## generated by rang

current.r.version <- paste(R.Version()[c("major","minor")], collapse = ".", sep = "")

if (Sys.getenv("CACHE_PATH") != "") {
    path <- file.path(Sys.getenv("CACHE_PATH"), "rpkgs")
} else {
    path <- tempdir()
}

.install.packages <- function(tarball.path, lib, verbose, current.r.version) {
    if (utils::compareVersion(current.r.version, "3.0") != -1) {
        if (is.na(lib)) {
            install.packages(pkg = tarball.path, repos = NULL, verbose = verbose, quiet = !verbose)
        } else {
            install.packages(pkg = tarball.path, lib = lib, repos = NULL, verbose = verbose, quiet = !verbose)
        }
    } else {
        if (is.na(lib)) {
            install.packages(pkg = tarball.path, repos = NULL)
        } else {
            install.packages(pkg = tarball.path, lib = lib, repos = NULL)
        }
    }
}

.download.package <- function(tarball.path, x, version, handle, source, uid, verbose, cran.mirror, bioc.mirror, current.r.version) {
    if (source == "github") {
        return(.download.package.from.github(tarball.path, x, version, handle, source, uid, current.r.version))
    }
    if (source == "bioc") {
        url <- paste(bioc.mirror, uid, "/src/contrib/", x, "_", version, ".tar.gz", sep = "")
    }
    if (source == "cran") {
        url <- paste(cran.mirror, "src/contrib/Archive/", x, "/", x, "_", version, ".tar.gz", sep = "")
    }

    tryCatch({
        suppressWarnings(download.file(url, destfile = tarball.path, quiet = !verbose))
    }, error = function(e) {
        if (source == "cran") {
            ## is the current latest
            url <- paste(cran.mirror, "src/contrib/", x, "_", version, ".tar.gz", sep = "")
            download.file(url, destfile = tarball.path, quiet = !verbose)
        }
    })
    invisible(tarball.path)
}

.tempfile <- function(tmpdir = tempdir(), fileext = ".tar.gz") {
    file.path(tmpdir,
    paste(paste(sample(c(LETTERS, letters), 20, replace = TRUE), collapse = ""), fileext, sep = ""))
}

.build.raw.tarball <- function(raw.tarball.path, x, version, tarball.path, current.r.version) {
    if (utils::compareVersion(current.r.version, "3.1") != -1) {
        vignetteflag <- "--no-build-vignettes"
    } else {
        vignetteflag <- "--no-vignettes"
    }
    tmp.dir <- .tempfile(fileext = "")
    dir.create(tmp.dir)
    system(command = paste("tar", "-zxf ", raw.tarball.path, "-C", tmp.dir))
    pkg.dir <- list.files(path = tmp.dir, full.names = TRUE)[1]
    new.pkg.dir <- file.path(tmp.dir, x)
    file.rename(pkg.dir, new.pkg.dir)
    res <- system(command = paste("R", "CMD", "build", vignetteflag, new.pkg.dir))
    expected.tarball.path <- paste(x, "_", version, ".tar.gz", sep = "")
    stopifnot(file.exists(expected.tarball.path))
    file.rename(expected.tarball.path, tarball.path)
    return(tarball.path)
}

.build.dir.tarball <- function(dir.pkg.path, x, version, tarball.path, current.r.version) {
    if (utils::compareVersion(current.r.version, "3.1") != -1) {
        vignetteflag <- "--no-build-vignettes"
    } else {
        vignetteflag <- "--no-vignettes"
    }
    expected.tarball.path <- paste(x, "_", version, ".tar.gz", sep = "")
    res <- system(command = paste("R", "CMD", "build", vignetteflag, dir.pkg.path))
    stopifnot(file.exists(expected.tarball.path))
    file.rename(expected.tarball.path, tarball.path)
    return(tarball.path)
}

.install.from.source <- function(x, version, handle, source, uid, lib,
                                 path = tempdir(), verbose, cran.mirror, bioc.mirror, current.r.version) {
    tarball.path <- file.path(path, paste(x, "_", version, ".tar.gz", sep = ""))
    raw.tarball.path <- file.path(path, paste("raw_", x, "_", version, ".tar.gz", sep = ""))
    dir.pkg.path <- file.path(path, paste("dir_", x, "_", version, sep = ""))
    if (!file.exists(tarball.path) && !file.exists(raw.tarball.path) && !file.exists(dir.pkg.path)) {
        .download.package(tarball.path = tarball.path, x = x, version = version, handle = handle, source = source,
                          uid = uid, verbose = verbose, cran.mirror = cran.mirror, bioc.mirror = bioc.mirror,
                          current.r.version = current.r.version)
    }
    if (file.exists(raw.tarball.path)) {
        tarball.path <- .build.raw.tarball(raw.tarball.path, x = x, version = version, tarball.path,
                                           current.r.version = current.r.version)
        if (!file.exists(tarball.path)) {
            stop("building failed.")
        }
    }
    if (file.exists(dir.pkg.path)) {
        tarball.path <- .build.dir.tarball(dir.pkg.path, x = x, version = version, tarball.path,
                                           current.r.version = current.r.version)
        if (!file.exists(tarball.path)) {
            stop("building failed.")
        }
    }
    .install.packages(tarball.path, lib, verbose, current.r.version)
    ## check and error
    if (!is.na(lib)) {
        installed.packages <- installed.packages(lib.loc = lib)
    } else {
        installed.packages <- installed.packages()
    }
    if (!x %in% dimnames(installed.packages)[[1]]) {
        stop("Fail to install ", x, "\n")
    }
    invisible()
}

# installing github packages
.download.github.safe <- function(handle, sha, file) {
    tryCatch(
        download.file(paste("http://api.github.com/repos/", handle, "/tarball/", sha, sep = ""), destfile = file),
        error = function(e) {
            stop(paste("couldn't download ", handle, " from github", sep = ""), call. = FALSE)
        }
    )
}

.download.package.from.github <- function(tarball.path, x, version, handle, source, uid, current.r.version) {
    sha <- uid
    short.sha <- substr(sha, 1, 7)
    raw.tarball.path <- .tempfile(fileext = ".tar.gz")
    tmp.dir <- tempdir()
    tryCatch(
        download.file(paste("https://api.github.com/repos/", handle, "/tarball/", sha, sep = ""), destfile = raw.tarball.path),
        error = function(e) {
            .download.github.safe(handle, sha, raw.tarball.path)
        }
    )
    .build.raw.tarball(raw.tarball.path = raw.tarball.path, x = x, version = version, tarball.path = tarball.path, current.r.version = current.r.version)
    return(tarball.path)
}
installation.order <- structure(list(x = c("cli", "glue", "isoband", "lattice", "rlang", 
"farver", "labeling", "colorspace", "R6", "RColorBrewer", "viridisLite", 
"fansi", "magrittr", "utf8", "pkgconfig", "withr", "matrixStats", 
"cpp11", "formatR", "futile.options", "snow", "codetools", "Rcpp", 
"BiocGenerics", "BH", "jsonlite", "GenomeInfoDbData", "abind", 
"crayon", "zlibbioc", "fs", "tximport", "curl", "mime", "sys", 
"generics", "stringi", "digest", "fastmap", "plogr", "png", "DBI", 
"rappdirs", "R.methodsS3", "polyclip", "lazyeval", "bit", "iterators", 
"permute", "cluster", "gridGraphics", "data.table", "fastmatch", 
"yaml", "clipr", "prettyunits", "statmod", "pixmap", "Rhdf5lib", 
"locfit", "lifecycle", "nlme", "Matrix", "mgcv", "munsell", "scales", 
"vctrs", "MatrixGenerics", "lambda.r", "futile.logger", "RcppArmadillo", 
"Biobase", "yulab.utils", "S4Vectors", "IRanges", "askpass", 
"openssl", "igraph", "plyr", "purrr", "stringr", "tidyselect", 
"blob", "cachem", "memoise", "httr2", "R.oo", "R.utils", "graphlayouts", 
"tweenr", "systemfonts", "RcppEigen", "ape", "bit64", "rhdf5filters", 
"rhdf5", "biomformat", "foreach", "survival", "multtest", "vegan", 
"downloader", "timechange", "lubridate", "snakecase", "hms", 
"progress", "tzdb", "xml2", "limma", "sp", "ade4", "BiocParallel", 
"gtable", "pillar", "tibble", "ggplot2", "httr", "UCSC.utils", 
"GenomeInfoDb", "S4Arrays", "XVector", "GenomicRanges", "reshape2", 
"qvalue", "dplyr", "tidyr", "RSQLite", "Biostrings", "KEGGREST", 
"AnnotationDbi", "GO.db", "gridExtra", "viridis", "tidygraph", 
"ggforce", "shadowtext", "tidytree", "treeio", "phyloseq", "ggplotify", 
"patchwork", "cowplot", "fgsea", "ggfun", "ggnewscale", "ggrepel", 
"janitor", "vroom", "readr", "GEOquery", "org.Hs.eg.db", "org.Mm.eg.db", 
"SparseArray", "DelayedArray", "SummarizedExperiment", "GOSemSim", 
"gson", "ggraph", "scatterpie", "aplot", "DOSE", "DESeq2", "ggtree", 
"enrichplot", "clusterProfiler"), version = c("3.6.3", "1.8.0", 
"0.2.7", "0.22-6", "1.1.4", "2.1.2", "0.4.3", "2.1-1", "2.5.1", 
"1.1-3", "0.4.2", "1.0.6", "2.0.3", "1.2.4", "2.0.3", "3.0.1", 
"1.4.1", "0.5.0", "1.14", "1.0.1", "0.4-4", "0.2-20", "1.0.13", 
"0.50.0", "1.84.0-0", "1.8.9", "1.2.12", "1.4-8", "1.5.3", "1.50.0", 
"1.6.4", "1.32.0", "5.2.3", "0.12", "3.4.2", "0.1.3", "1.8.4", 
"0.6.37", "1.2.0", "0.2.0", "0.1-8", "1.2.3", "0.3.3", "1.8.2", 
"1.10-7", "0.2.2", "4.5.0", "1.0.14", "0.9-7", "2.1.6", "0.5-1", 
"1.16.0", "1.1-4", "2.3.10", "0.8.0", "1.2.0", "1.5.0", "0.4-13", 
"1.26.0", "1.5-9.10", "1.0.4", "3.1-166", "1.7-0", "1.9-1", "0.5.1", 
"1.3.0", "0.6.5", "1.16.0", "1.2.4", "1.4.3", "14.0.2-1", "2.64.0", 
"0.1.7", "0.42.1", "2.38.1", "1.2.0", "2.2.2", "2.0.3", "1.8.9", 
"1.0.2", "1.5.1", "1.2.1", "1.2.4", "1.1.0", "2.0.1", "1.0.5", 
"1.26.0", "2.12.3", "1.2.0", "2.0.3", "1.1.0", "0.3.4.0.2", "5.8", 
"4.5.2", "1.16.0", "2.48.0", "1.32.0", "1.5.2", "3.7-0", "2.60.0", 
"2.6-8", "0.4", "0.3.0", "1.9.3", "0.11.1", "1.1.3", "1.2.3", 
"0.4.0", "1.3.6", "3.60.6", "2.1-4", "1.7-22", "1.38.0", "0.3.5", 
"1.9.0", "3.2.1", "3.5.1", "1.4.7", "1.0.0", "1.40.1", "1.4.1", 
"0.44.0", "1.56.2", "1.4.4", "2.36.0", "1.1.4", "1.3.1", "2.3.7", 
"2.72.1", "1.44.1", "1.66.0", "3.19.1", "2.3", "0.6.5", "1.3.1", 
"0.4.2", "0.1.4", "0.4.6", "1.28.0", "1.48.0", "0.1.2", "1.3.0", 
"1.1.3", "1.30.0", "0.1.6", "0.5.0", "0.9.6", "2.2.0", "1.6.5", 
"2.1.5", "2.72.0", "3.19.1", "3.19.1", "1.4.8", "0.30.1", "1.34.0", 
"2.30.2", "0.1.0", "2.2.1", "0.2.4", "0.2.3", "3.30.5", "1.44.0", 
"3.12.0", "1.24.4", "4.12.6"), source = c("cran", "cran", "cran", 
"cran", "cran", "cran", "cran", "cran", "cran", "cran", "cran", 
"cran", "cran", "cran", "cran", "cran", "cran", "cran", "cran", 
"cran", "cran", "cran", "cran", "bioc", "cran", "cran", "bioc", 
"cran", "cran", "bioc", "cran", "bioc", "cran", "cran", "cran", 
"cran", "cran", "cran", "cran", "cran", "cran", "cran", "cran", 
"cran", "cran", "cran", "cran", "cran", "cran", "cran", "cran", 
"cran", "cran", "cran", "cran", "cran", "cran", "cran", "bioc", 
"cran", "cran", "cran", "cran", "cran", "cran", "cran", "cran", 
"bioc", "cran", "cran", "cran", "bioc", "cran", "bioc", "bioc", 
"cran", "cran", "cran", "cran", "cran", "cran", "cran", "cran", 
"cran", "cran", "cran", "cran", "cran", "cran", "cran", "cran", 
"cran", "cran", "cran", "bioc", "bioc", "bioc", "cran", "cran", 
"bioc", "cran", "cran", "cran", "cran", "cran", "cran", "cran", 
"cran", "cran", "bioc", "cran", "cran", "bioc", "cran", "cran", 
"cran", "cran", "cran", "bioc", "bioc", "bioc", "bioc", "bioc", 
"cran", "bioc", "cran", "cran", "cran", "bioc", "bioc", "bioc", 
"bioc", "cran", "cran", "cran", "cran", "cran", "cran", "bioc", 
"bioc", "cran", "cran", "cran", "bioc", "cran", "cran", "cran", 
"cran", "cran", "cran", "bioc", "bioc", "bioc", "bioc", "bioc", 
"bioc", "bioc", "cran", "cran", "cran", "cran", "bioc", "bioc", 
"bioc", "bioc", "bioc"), handle = c("cli", "glue", "isoband", 
"lattice", "rlang", "farver", "labeling", "colorspace", "R6", 
"RColorBrewer", "viridisLite", "fansi", "magrittr", "utf8", "pkgconfig", 
"withr", "matrixStats", "cpp11", "formatR", "futile.options", 
"snow", "codetools", "Rcpp", "BiocGenerics", "BH", "jsonlite", 
"GenomeInfoDbData", "abind", "crayon", "zlibbioc", "fs", "tximport", 
"curl", "mime", "sys", "generics", "stringi", "digest", "fastmap", 
"plogr", "png", "DBI", "rappdirs", "R.methodsS3", "polyclip", 
"lazyeval", "bit", "iterators", "permute", "cluster", "gridGraphics", 
"data.table", "fastmatch", "yaml", "clipr", "prettyunits", "statmod", 
"pixmap", "Rhdf5lib", "locfit", "lifecycle", "nlme", "Matrix", 
"mgcv", "munsell", "scales", "vctrs", "MatrixGenerics", "lambda.r", 
"futile.logger", "RcppArmadillo", "Biobase", "yulab.utils", "S4Vectors", 
"IRanges", "askpass", "openssl", "igraph", "plyr", "purrr", "stringr", 
"tidyselect", "blob", "cachem", "memoise", "httr2", "R.oo", "R.utils", 
"graphlayouts", "tweenr", "systemfonts", "RcppEigen", "ape", 
"bit64", "rhdf5filters", "rhdf5", "biomformat", "foreach", "survival", 
"multtest", "vegan", "downloader", "timechange", "lubridate", 
"snakecase", "hms", "progress", "tzdb", "xml2", "limma", "sp", 
"ade4", "BiocParallel", "gtable", "pillar", "tibble", "ggplot2", 
"httr", "UCSC.utils", "GenomeInfoDb", "S4Arrays", "XVector", 
"GenomicRanges", "reshape2", "qvalue", "dplyr", "tidyr", "RSQLite", 
"Biostrings", "KEGGREST", "AnnotationDbi", "GO.db", "gridExtra", 
"viridis", "tidygraph", "ggforce", "shadowtext", "tidytree", 
"treeio", "phyloseq", "ggplotify", "patchwork", "cowplot", "fgsea", 
"ggfun", "ggnewscale", "ggrepel", "janitor", "vroom", "readr", 
"GEOquery", "org.Hs.eg.db", "org.Mm.eg.db", "SparseArray", "DelayedArray", 
"SummarizedExperiment", "GOSemSim", "gson", "ggraph", "scatterpie", 
"aplot", "DOSE", "DESeq2", "ggtree", "enrichplot", "clusterProfiler"
), uid = c(NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, 
NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, "bioc", NA, NA, "data/annotation", 
NA, NA, "bioc", NA, "bioc", NA, NA, NA, NA, NA, NA, NA, NA, NA, 
NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, 
NA, "bioc", NA, NA, NA, NA, NA, NA, NA, NA, "bioc", NA, NA, NA, 
"bioc", NA, "bioc", "bioc", NA, NA, NA, NA, NA, NA, NA, NA, NA, 
NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, "bioc", "bioc", "bioc", 
NA, NA, "bioc", NA, NA, NA, NA, NA, NA, NA, NA, NA, "bioc", NA, 
NA, "bioc", NA, NA, NA, NA, NA, "bioc", "bioc", "bioc", "bioc", 
"bioc", NA, "bioc", NA, NA, NA, "bioc", "bioc", "bioc", "data/annotation", 
NA, NA, NA, NA, NA, NA, "bioc", "bioc", NA, NA, NA, "bioc", NA, 
NA, NA, NA, NA, NA, "bioc", "data/annotation", "data/annotation", 
"bioc", "bioc", "bioc", "bioc", NA, NA, NA, NA, "bioc", "bioc", 
"bioc", "bioc", "bioc")), class = "data.frame", row.names = c(NA, 
-166L))

verbose <- TRUE
lib <- NA
cran.mirror <- "https://cran.r-project.org/"
bioc.mirror <- "https://bioconductor.org/packages/3.19/"

if (nrow(installation.order) >= 1) {
    for (i in seq(from = 1, to = nrow(installation.order), by = 1)) {
        x <- installation.order$x[i]
        source <- installation.order$source[i]
        version <- installation.order$version[i]
        handle <- installation.order$handle[i]
        uid <- installation.order$uid[i]
        .install.from.source(x = x, version = version, handle = handle, source = source, uid = uid,
                             lib = lib, path = path, verbose = verbose,
                             cran.mirror = cran.mirror, bioc.mirror = bioc.mirror,
                             current.r.version = current.r.version)
    }
}
